asm/io.h: fix file not found error on compile
arch/arm/include/asm/io.h:30:26: fatal error: mach/msm_rtb.h: No such file or directory

This error is because the compiler tries looking in arch/arm/include/asm/mach
which is incorrect behavior. To fix this, go back one directory and
then to the proper file.

Signed-off-by: Simon Sickle <simon@simonsickle.com>

Change-Id: I0df6787f622a3fd87f6c9f4c8fec2514894918b1